the list comprehension is faster but creates an Internal Server 500 error  ```return [l for l in my_posts if l['id'] == id][0]
IndexError: list index out of range```  so switching to slower for-loop that doesnt cause that error and instead just Data Null returned